project_id = "hulwcntfioqifopyjcvv"

[functions.cobcloud-proxy]
verify_jwt = false

[functions.send-notifications]
verify_jwt = false

[functions.portal-lookup]
verify_jwt = false

[functions.negociarie-proxy]
verify_jwt = false

[functions.negociarie-callback]
verify_jwt = false

[functions.send-bulk-whatsapp]
verify_jwt = false

[functions.evolution-proxy]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false

[functions.chat-ai-suggest]
verify_jwt = false

[functions.portal-checkout]
verify_jwt = false

[functions.calculate-propensity]
verify_jwt = false

[functions.clients-api]
verify_jwt = false

[functions.check-sla-expiry]
verify_jwt = false
